#CI项目
name: IPQ807X-6.12-WIFI

#CI计划
on:
  #自动编译：每个星期五凌晨
#  schedule:
#    - cron: 0 16 * * 5
  #推送代码编译
  #push:
  workflow_call:
    inputs:
      SOURCE:
        description: 'repo source name. [ LiBwrt-op/openwrt-6.x, laipeng668/openwrt-6.x, laipeng668/immortalwrt, immortalwrt/immortalwrt ]'
        default: 'LiBwrt-op/openwrt-6.x'
        required: true
        type: string
      BRANCH:
        default: 'k6.12-nss'
        required: true
        description: 'branch name. [ master, main, k6.12-nss ]'
        type: string
  workflow_dispatch:
    inputs:
      SOURCE:
        default: 'LiBwrt-op/openwrt-6.x'
        required: true
        type: choice
        description: 'repo source name'
        options: [ 'LiBwrt-op/openwrt-6.x', 'laipeng668/openwrt-6.x', 'laipeng668/immortalwrt', 'immortalwrt/immortalwrt' ]
      BRANCH:
        default: 'k6.12-nss'
        required: true
        description: 'branch name'
        type: choice
        options:
          - master
          - main
          - k6.12-nss
      COMMIT:
        required: false
        description: '可编译代码commit id'
        type: string
      PACKAGE:
        required: false
        description: 'add package name'
        type: string
      PATCH:
        description: '打patch开关'
        required: true
        default: '否'
        type: choice
        options: [是, 否]
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: '否'
        required: false
        type: choice
        options: [是, 否]

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: IPQ807X
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        TARGET: [ IPQ807X ]
        SOURCE: [ LiBwrt-op/openwrt-6.x ]
        BRANCH: [ k6.12-nss ]
    #调用公用编译核心XX-CORE.yml
    uses: ./.github/workflows/6.12-WIFI-CORE.yml
    with:
      #编译平台
      WRT_TARGET: ${{matrix.TARGET}}
      #源码链接
      WRT_REPO: https://github.com/${{inputs.SOURCE || matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{inputs.BRANCH || matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{inputs.SOURCE || matrix.SOURCE}}
      #patch开关
      WRT_PATCH: ${{inputs.PATCH || '否'}}
      #回滚到指定commit
      WRT_COMMIT: ${{inputs.COMMIT}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
